"""controller sz api auth fields

Revision ID: 0a37b1b37a6f
Revises: ca9668a75fcb
Create Date: 2026-07-03 23:06:00.906437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a37b1b37a6f'
down_revision: Union[str, Sequence[str], None] = 'ca9668a75fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_username', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('api_password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('api_version', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_column('api_version')
        batch_op.drop_column('api_password')
        batch_op.drop_column('api_username')

    # ### end Alembic commands ###
