"""target mac column

Revision ID: 8c3c2f7f21a7
Revises: 8d62ac7998c1
Create Date: 2026-07-08 18:54:02.832989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3c2f7f21a7'
down_revision: Union[str, Sequence[str], None] = '8d62ac7998c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_column('mac')

    # ### end Alembic commands ###
