"""assignment width_mhz + target venue_id

Revision ID: 8d62ac7998c1
Revises: 9095c2453e8b
Create Date: 2026-07-05 19:21:50.842892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d62ac7998c1'
down_revision: Union[str, Sequence[str], None] = '9095c2453e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_mhz', sa.Integer(), nullable=True))

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_column('venue_id')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('width_mhz')

    # ### end Alembic commands ###
