"""drop controller ssh creds

Revision ID: 9095c2453e8b
Revises: 0a37b1b37a6f
Create Date: 2026-07-04 01:47:46.796380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9095c2453e8b'
down_revision: Union[str, Sequence[str], None] = '0a37b1b37a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_column('ssh_password')
        batch_op.drop_column('ssh_username')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_username', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('ssh_password', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
