"""initial schema

Revision ID: ca9668a75fcb
Revises: 
Create Date: 2026-07-03 17:10:46.430557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9668a75fcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=40), nullable=True),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.Column('api_client_id', sa.String(length=255), nullable=True),
    sa.Column('api_client_secret', sa.Text(), nullable=True),
    sa.Column('ssh_username', sa.String(length=64), nullable=False),
    sa.Column('ssh_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controllers'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('ended_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_artifacts_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_table('targets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('controller_id', sa.String(length=32), nullable=True),
    sa.Column('ssh_username', sa.String(length=64), nullable=True),
    sa.Column('ssh_password', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_targets_controller_id_controllers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    op.create_table('assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('ap_host', sa.String(length=64), nullable=False),
    sa.Column('iface', sa.String(length=16), nullable=False),
    sa.Column('target_channel', sa.Integer(), nullable=True),
    sa.Column('flags', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('linktype', sa.Integer(), nullable=True),
    sa.Column('frames', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('sidecar', sa.JSON(), nullable=True),
    sa.Column('host_key_fingerprint', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('ended_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_assignments_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_assignments_target_id_targets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('targets')
    op.drop_table('artifacts')
    op.drop_table('templates')
    op.drop_table('sessions')
    op.drop_table('controllers')
    # ### end Alembic commands ###
